version: 2

models:
  - name: fact_enrollments
    description: "A record for each enrollment event"
    columns:
      - name: emission_time
        data_type: DateTime
        description: "Timestamp, to the second, of when this event was emitted"
      - name: org
        data_type: String
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: String
        description: "The course key for the course"
      - name: course_name
        data_type: String
        description: "The name of the course"
      - name: course_run
        data_type: String
        description: "The course run for the course"
      - name: actor_id
        data_type: String
        description: "The xAPI actor identifier"
      - name: enrollment_mode
        data_type: LowCardinality(String)
        description: "The mode of enrollment"
      - name: enrollment_status
        description: "Whether a learner is actively enrolled in a course"
        tests:
          - accepted_values:
              values: ["registered", "unregistered"]
        data_type: String
      - name: username
        data_type: String
        description: "The username of the learner"
      - name: name
        data_type: String
        description: "The full name of the learner"
      - name: email
        data_type: String
        description: "The email address of the learner"

  - name: enrollment_events
    description: "A materialized view for xAPI events related to course enrollment"
    columns:
      - name: event_id
        data_type: uuid
        description: "The unique identifier for the event"
      - name: emission_time
        data_type: datetime
        description: "The time the event was emitted"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: object_id
        data_type: string
        description: "The xAPI object identifier"
      - name: course_key
        data_type: string
        description: "The course identifier"
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: verb_id
        data_type: string
        description: "The xAPI verb identifier"
      - name: enrollment_mode
        data_type: string
        description: "The mode of enrollment"

  - name: fact_enrollment_status
    description: One record per learner per course for the most recent enrollment status
    columns:
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: string
        description: "The course key for the course"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: enrollment_status
        data_type: string
        description: "Whether a learner is actively enrolled in a course"
        tests:
          - accepted_values:
              values: ["registered", "unregistered"]
      - name: enrollment_mode
        data_type: string
        description: "The mode of enrollment"
      - name: emission_time
        data_type: datetime
        description: "The time the enrollment status was emitted"
