version: 2

models:
  - name: fact_grades
    description: "One record per grading event for courses, subsections, and problems"
    columns:
      - name: emission_time
        description: "Timestamp, to the second, of when this event was emitted"
        data_type: DateTime64(3)
      - name: org
        data_type: String
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: String
        description: "The course key for the course"
      - name: course_name
        data_type: String
        description: "The name of the course"
      - name: course_run
        data_type: String
        description: "The course run for the course"
      - name: entity_id
        description: "The block ID or course key for the graded entity"
        data_type: String
      - name: entity_name
        data_type: String
        description: "The name of the graded entity (course or block)"
      - name: entity_name_with_location
        data_type: Nullable(String)
        description: "The entity's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at block names and can help data consumers understand which block they are analyzing"
      - name: grade_type
        description: "The type of object graded"
        tests:
          - accepted_values:
              values: ["course", "subsection", "problem"]
        data_type: Nullable(String)
      - name: actor_id
        data_type: String
        description: "The xAPI actor identifier"
      - name: scaled_score
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
        data_type: Float32
      - name: grade_bucket
        description: "A displayable value of grades sorted into 10% buckets. Useful for grouping grades together to show high-level learner performance"
        data_type: String

  - name: fact_grade_status
    description: "One record per learner per course for the most recent grade and approving status"
    columns:
      - name: org
        data_type: String
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: String
        description: "The course key for the course"
      - name: actor_id
        data_type: String
        description: "The xAPI actor identifier"
      - name: course_name
        data_type: String
        description: "The name of the course"
      - name: course_run
        data_type: String
        description: "The course run for the course"
      - name: state
        description: "The most recent state of the learner's grade"
        tests:
          - accepted_values:
              values: ["passed", "failed"]
        data_type: String
      - name: course_grade
        description: "The most recent grade for the learner"
        data_type: Float32
      - name: grade_bucket
        description: "A displayable value of grades sorted into 10% buckets. Useful for grouping grades together to show high-level learner performance"
        data_type: String

  - name: fact_learner_course_grade
    description: "One record per learner per course for the most recent grade"
    columns:
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: string
        description: "The course key for the course"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: course_grade
        data_type: float64
        description: "The most recent grade for the learner"

  - name: fact_learner_course_status
    description: "One record per learner per course for the most recent approving status"
    columns:
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: string
        description: "The course key for the course"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: state
        data_type: string
        description: "The most recent state of the learner's grade"
        tests:
          - accepted_values:
              values: ["passed", "failed"]

  - name: grading_events
    description: "Events related to grading"
    columns:
      - name: event_id
        data_type: uuid
        description: "The unique identifier for the event"
      - name: emission_time
        data_type: datetime
        description: "The time the event was emitted"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: object_id
        data_type: string
        description: "The xAPI object identifier"
      - name: course_key
        data_type: string
        description: "The course identifier"
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: verb_id
        data_type: string
        description: "The xAPI verb identifier"
      - name: scaled_score
        data_type: float64
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
