version: 2

models:
  - name: dim_learner_most_recent_course_grade
    description: "One record per learner per course for the most recent grade"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: course_grade
        data_type: float64
        description: "The most recent grade for the learner"
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'


  - name: dim_learner_most_recent_course_state
    description: "One record per learner per course for the most recent approving status"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'
      - name: approving_state
        data_type: String
        description: "The most recent approving_state of the learner's grade"
        data_tests:
          - accepted_values:
              values: ["passed", "failed"]

  - name: grading_events
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "Events related to grading"
    columns:
      - name: event_id
        data_type: UUID
        description: '{{ doc("event_id") }}'
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: object_id
        data_type: String
        description: '{{ doc("object_id") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: verb_id
        data_type: String
        description: '{{ doc("verb_id") }}'
      - name: scaled_score
        data_type: float64
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
      - name: approving_state
        data_type: String
        description: "The most recent approving_state of the learner's grade"

  - name: dim_student_status
    description: "One record per learner per course for the most recent grade and enrollment status"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: course_name
        data_type: String
        description: '{{ doc("course_name") }}'
      - name: course_run
        data_type: String
        description: '{{ doc("course_run") }}'
      - name: approving_state
        data_type: String
        description: "The most recent approving state for the learner"
      - name: enrollment_mode
        data_type: String
        description: '{{ doc("enrollment_mode") }}'
      - name: enrollment_status
        description: '{{ doc("enrollment_status") }}'
        data_tests:
          - accepted_values:
              values: ["registered", "unregistered"]
      - name: course_grade
        data_type: float64
        description: "The most recent grade for the learner"
      - name: grade_bucket
        data_type: String
        description: "A displayable value of grades sorted into 10% buckets. Useful for grouping grades together to show high-level learner performance"
      - name: username
        data_type: String
        description: '{{ doc("username") }}'
      - name: name
        data_type: String
        description: '{{ doc("learner_name") }}'
      - name: email
        data_type: String
        description: '{{ doc("email") }}'
      - name: enrolled_at
        data_type: DateTime
        description: "The timestamp, to the second, of the most recent enrollment action for this learner and course."
