version: 2

models:

  - name: user_pii
    description: "The user PII table for reports."
    columns:
      - name: user_id
        data_type: String
        description: "The user id"
      - name: external_user_id
        data_type: String
        description: "The external user id"
      - name: username
        data_type: String
        description: "The username of the user"
      - name: name
        data_type: String
        description: "The name of the user"
      - name: email
        data_type: String
        description: "The email of the user"

  - name: dim_user_pii
    description: "A denormalized table of user PII information"
    columns:
      - name: external_user_id
        data_type: String
        description: "The external user id"
      - name: username
        data_type: String
        description: "The username"
      - name: name
        data_type: String
        description: "The name of the user"
      - name: email
        data_type: String
        description: "The email of the user"
