version: 2

models:
  - name: problem_events
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "Problem events"
    columns:
      - name: event_id
        data_type: UUID
        description: '{{ doc("event_id") }}'
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: object_id
        data_type: String
        description: '{{ doc("object_id") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: verb_id
        data_type: String
        description: '{{ doc("verb_id") }}'
      - name: responses
        data_type: String
        description: "The responses for this submission. If a problem has multiple parts, values for all parts will be in this field"
      - name: scaled_score
        data_type: Float32
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
      - name: success
        data_type: Boolean
        description: "Boolean indicating whether the responses were correct"
      - name: interaction_type
        data_type: String
        description: "The type of interaction"
      - name: attempts
        data_type: Int16
        description: "Number indicating which attempt this was"
      - name: problem_id
        data_type: String
        description: "The problem's unique identifier"
      - name: course_name
        data_type: String
        description: '{{ doc("course_name") }}'
      - name: block_name
        data_type: String
        description: "The name of the block"
      - name: display_name_with_location
        data_type: String
        description: "The block's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at block names and can help data consumers understand which block they are analyzing"      
      - name: problem_link
        data_type: String
        description: "An anchor tag with a link to the problem"
      - name: graded
        data_type: bool
        description: '{{ doc("graded") }}'
      - name: course_order
        data_type: Int32
        description: '{{ doc("course_order") }}'

  - name: dim_learner_response_attempt
    description: "One record per course per problem per learner with their last attempt and first success"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: problem_id
        data_type: String
        description: "The problem's unique identifier"
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: first_success_at
        data_type: Nullable(DateTime)
        description: "The timestamp of the first successful attempt"
      - name: last_attempt_at
        data_type: DateTime
        description: "The timestamp of the last attempt"
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'

  - name: fact_problem_engagement
    description: "A record per course per section and subsection per learner with their engagement level"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: course_run
        data_type: String
        description: '{{ doc("course_run") }}'
      - name: section_subsection_name
        data_type: String
        description: '{{ doc("section_with_name") }}'
      - name: content_level
        data_type: String
        description: 'Identifies section data vs subsection data'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: section_subsection_problem_engagement
        data_type: String
        description: "The engagement level of the learner with the section"
        data_tests:
          - accepted_values:
              values:
                - 'No problems attempted yet'
                - 'All problems attempted'
                - 'At least one problem attempted'
      - name: username
        data_type: String
        description: '{{ doc("username") }}'
      - name: name
        data_type: String
        description: '{{ doc("learner_name") }}'
      - name: email
        data_type: String
        description: '{{ doc("email") }}'
