version: 2

models:
  - name: problem_events
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "Problem events"
    columns:
      - name: event_id
        data_type: UUID
        description: '{{ doc("event_id") }}'
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: object_id
        data_type: String
        description: '{{ doc("object_id") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: verb_id
        data_type: String
        description: '{{ doc("verb_id") }}'
      - name: responses
        data_type: String
        description: "The responses for this submission. If a problem has multiple parts, values for all parts will be in this field"
      - name: scaled_score
        data_type: Float32
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
      - name: success
        data_type: Boolean
        description: '{{ doc("success") }}'
      - name: interaction_type
        data_type: String
        description: "The type of interaction"
      - name: attempts
        data_type: Int16
        description: '{{ doc("attempts") }}'
      - name: problem_id
        data_type: String
        description: "The problem's unique identifier"
      - name: course_name
        data_type: String
        description: '{{ doc("course_name") }}'
      - name: block_name
        data_type: String
        description: "The name of the block"

  - name: dim_learner_last_response
    description: "A record per course per problem per learner with their last attempt"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: problem_id
        data_type: String
        description: "The problem's unique identifier"
      - name: display_name_with_location
        data_type: String
        description: "The block's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at block names and can help data consumers understand which block they are analyzing"      
      - name: problem_link
        data_type: String
        description: "An anchor tag with a link to the problem"
      - name: graded
        data_type: bool
        description: '{{ doc("graded") }}'
      - name: object_id
        data_type: String
        description: '{{ doc("object_id") }}'
      - name: course_order
        data_type: Int32
        description: '{{ doc("course_order") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: interaction_type
        data_type: String
        description: 'The type of problem (choice, numeric, etc)'
      - name: attempts
        data_type: Int16
        description: '{{ doc("attempts") }}'
      - name: success
        data_type: Boolean
        description: '{{ doc("success") }}'
      - name: responses
        data_type: String
        description: "The responses for the last submission. If a problem has multiple parts, values for all parts will be in this field"
      - name: scaled_score
        data_type: Float32
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
      - name: emission_time
        data_type: DateTime
        description: "The timestamp of the last attempt"

  - name: dim_problem_responses
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: interaction_type
        data_type: String
        description: 'The type of problem (choice, numeric, etc)'
      - name: success
        data_type: Boolean
        description: '{{ doc("success") }}'
      - name: response
        data_type: String
        description: "The response for the first submission for a single part of a single problem. All formatting is removed."
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'
      - name: block_id_short
        data_type: String
        description: '{{ doc("block_id") }}'
      - name: problem_number
        data_type: String
        description: '{{ doc("problem_number") }}'
      - name: problem_name_location
        data_type: String
        description: "problem_number followed by the name of the problem"
      - name: response_count
        data_type: Int64
        description: "Count of each response per problem part"

  - name: dim_problem_results
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: success
        data_type: Boolean
        description: '{{ doc("success") }}'
      - name: attempts
        data_type: Int16
        description: '{{ doc("attempts") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: problem_number
        data_type: String
        description: '{{ doc("problem_number") }}'
      - name: problem_name_location
        data_type: String
        description: "problem_number followed by the name of the problem"
      - name: block_id_short
        data_type: String
        description: '{{ doc("block_id") }}'

  - name: dim_subsection_problem_results
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: success
        data_type: Boolean
        description: '{{ doc("success") }}'
      - name: block_id_short
        data_type: String
        description: '{{ doc("block_id") }}'
      - name: problem_number
        data_type: String
        description: '{{ doc("problem_number") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: subsection_number
        data_type: String
        description: 'Subsection location in the format 1:2:0'
      - name: subsection_with_name
        data_type: String
        description: 'subsection_number followed by subsection name'
      - name: scaled_score
        data_type: Float32
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
      - name: problem_name_location
        data_type: String
        description: "problem_number followed by the name of the problem"

  - name: fact_problem_engagement
    description: "A record per course per section and subsection per learner with engagement level"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: section_subsection_name
        data_type: String
        description: 'Section or Subsection name'
      - name: section_with_name
        data_type: String
        description: '{{ doc("section_with_name") }}'
      - name: content_level
        data_type: String
        description: "The level at which page views are counted"
        data_tests:
          - accepted_values:
              values: ["section", "subsection"]
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: section_subsection_problem_engagement
        data_type: UInt64
        description: "The total number of times a learner engaged with a problem in this section or subsection" 
      - name: block_id
        data_type: String
        description: '{{ doc("block_id") }}'
      - name: username
        data_type: String
        description: '{{ doc("username") }}'
      - name: name
        data_type: String
        description: '{{ doc("learner_name") }}'
      - name: email
        data_type: String
        description: '{{ doc("email") }}'
