version: 2

models:
  - name: fact_learner_problem_summary
    description: "One record per learner per problem in a course"
    columns:
      - name: org
        data_type: String
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: String
        description: "The course key for the course"
      - name: course_name
        data_type: String
        description: "The name of the course"
      - name: course_run
        data_type: String
        description: "The course run for the course"
      - name: problem_id
        data_type: String
        description: "The problem's unique identifier"
      - name: problem_name
        data_type: String
        description: "The problem's name"
      - name: problem_name_with_location
        data_type: String
        description: "The problem's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at problem names and can help data consumers understand which problem they are analyzing"
      - name: actor_id
        data_type: String
        description: "The xAPI actor identifier"
      - name: success
        description: "The result of the last submission"
        tests:
          - not_null
        data_type: Bool
      - name: attempts
        description: "The number of attempts made"
        tests:
          - not_null
        data_type: Int16
      - name: num_hints_displayed
        description: "The number of times a learner asked for a hint"
        data_type: UInt64
      - name: num_answers_displayed
        description: "The number of times a learner requested the answers for the problem"
        data_type: UInt64

  - name: fact_problem_responses
    description: "One record for each submitted response to a problem"
    columns:
      - name: emission_time
        data_type: DateTime
        description: "Timestamp, to the second, of when this event was emitted"
      - name: org
        data_type: String
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: String
        description: "The course key for the course"
      - name: course_name
        data_type: String
        description: "The name of the course"
      - name: course_run
        data_type: String
        description: "The course run for the course"
      - name: problem_id
        data_type: String
        description: "The problem's unique identifier"
      - name: problem_name
        data_type: String
        description: "The problem's name"
      - name: problem_name_with_location
        data_type: String
        description: "The problem's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at problem names and can help data consumers understand which problem they are analyzing"
      - name: problem_link
        data_type: String
        description: "An anchor tag with a link to the problem"
      - name: actor_id
        data_type: String
        description: "The xAPI actor identifier"
      - name: responses
        description: "The responses for this submission. If a problem has multiple parts, values for all parts will be in this field"
        data_type: String
      - name: success
        description: "Boolean indicating whether the responses were correct"
        data_type: Bool
      - name: attempts
        description: "Number indicating which attempt this was"
        data_type: Int16
      - name: graded
        data_type: bool
        description: "Boolean indicating this block is graded"

  - name: int_problem_hints
    description: "Internal table for problem hints"
    columns:
      - name: emission_time
        data_type: datetime
        description: "Timestamp, to the second, of when this event was emitted"
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: string
        description: "The course key for the course"
      - name: course_name
        data_type: string
        description: "The name of the course"
      - name: course_run
        data_type: string
        description: "The course run for the course"
      - name: problem_id
        data_type: string
        description: "The problem's unique identifier"
      - name: problem_name
        data_type: string
        description: "The problem's name"
      - name: problem_name_with_location
        data_type: string
        description: "The problem's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at problem names and can help data consumers understand which problem they are analyzing"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: help_type
        data_type: string
        description: "The type of help requested"

  - name: int_problem_results
    description: "Internal table for problem results"
    columns:
      - name: emission_time
        data_type: datetime
        description: "Timestamp, to the second, of when this event was emitted"
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: string
        description: "The course key for the course"
      - name: course_name
        data_type: string
        description: "The name of the course"
      - name: course_run
        data_type: string
        description: "The course run for the course"
      - name: problem_id
        data_type: string
        description: "The problem's unique identifier"
      - name: problem_name
        data_type: string
        description: "The problem's name"
      - name: problem_name_with_location
        data_type: string
        description: "The problem's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at problem names and can help data consumers understand which problem they are analyzing"
      - name: problem_link
        data_type: String
        description: "An anchor tag with a link to the problem"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: responses
        data_type: string
        description: "The responses for this submission. If a problem has multiple parts, values for all parts will be in this field"
      - name: success
        data_type: bool
        description: "Boolean indicating whether the responses were correct"
      - name: attempts
        data_type: int16
        description: "Number indicating which attempt this was"

  - name: problem_events
    description: "Problem events"
    columns:
      - name: event_id
        data_type: uuid
        description: "The unique identifier for the event"
      - name: emission_time
        data_type: datetime
        description: "The time the event was emitted"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: object_id
        data_type: string
        description: "The xAPI object identifier"
      - name: course_key
        data_type: string
        description: "The course identifier"
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: verb_id
        data_type: string
        description: "The xAPI verb identifier"
      - name: responses
        data_type: string
        description: "The responses for this submission. If a problem has multiple parts, values for all parts will be in this field"
      - name: scaled_score
        data_type: string
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
      - name: success
        data_type: bool
        description: "Boolean indicating whether the responses were correct"
      - name: interaction_type
        data_type: string
        description: "The type of interaction"
      - name: attempts
        data_type: int16
        description: "Number indicating which attempt this was"

  - name: int_problems_per_subsection
    description: "A dimension table with the number of problems per subsection"
    columns:
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: string
        description: "The course key for the course"
      - name: section_number
        data_type: string
        description: "The location of this section in the course, represented as section:0:0"
      - name: section_with_name
        data_type: string
        description: "The name of the section this subsection belongs to, with section_number prepended"
      - name: subsection_number
        data_type: string
        description: "The location of this subsection in the course, represented as section:subsection:0"
      - name: subsection_with_name
        data_type: string
        description: "The name of the subsection, with section_number prepended"
      - name: graded
        data_type: bool
        description: "Whether this subsection block is graded"
      - name: item_count
        data_type: uint64
        description: "The number of problems in this subsection"

  - name: fact_problem_engagement
    description: "A dataset with one record representing a problem attempted by a learner and the section and subsection that problem belongs to"
    columns:
      - name: attempted_on
        data_type: date
        description: "The date on which the problem was attempted"
      - name: org
        data_type: string
        description: "The organization that the problem belongs to"
      - name: course_key
        data_type: string
        description: "The course key for the course"
      - name: course_run
        data_type: string
        description: "The course run for the course"
      - name: section_with_name
        data_type: string
        description: "The name of the section this subsection belongs to, with section_number prepended"
      - name: subsection_with_name
        data_type: string
        description: "The name of the subsection, with section_number prepended"
      - name: item_count
        data_type: uint64
        description: "The number of problems in this subsection"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: problem_id
        data_type: string
        description: "The xAPI object identifier"
      - name: graded
        data_type: bool
        description: "Whether the block is graded"
