version: 2

models:
  - name: fact_instance_courses
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "A materialized view summarizing site-wide course activity"
    columns:
      - name: emission_hour
        data_type: DateTime(64)
        description: "Time of summary, rounded to the nearest hour"
      - name: courses_cnt
        data_type: Int
        description: "The number of xAPI courses active in the given hour"

  - name: fact_instance_events
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "A materialized view summarizing site-wide xAPI event activity"
    columns:
      - name: emission_day
        data_type: DateTime
        description: "Time of summary, truncated to the day"
      - name: events_cnt
        data_type: Int
        description: "The number of xAPI events that occurred in the given hour"

  - name: fact_instance_actors
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "A materialized view summarizing site-wide user activity"
    columns:
      - name: emission_day
        data_type: DateTime
        description: "Time of summary, truncated to the day"
      - name: actors_cnt
        data_type: Int
        description: "The number of xAPI actors active in the given hour"

  - name: fact_instance_enrollments
    description: "A materialized view for summarizing site-wide enrollment activity"
    columns:
      - name: emission_day
        data_type: DateTime
        description: "Time of summary, truncated to the day"
      - name: course_name
        data_type: String
        description: '{{ doc("course_name") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: enrollment_mode
        data_type: String
        description: '{{ doc("enrollment_mode") }}'
      - name: enrollment_status
        data_type: String
        description: '{{ doc("enrollment_status") }}'
        data_tests:
          - accepted_values:
              values: [ "registered", "unregistered" ]
      - name: course_enrollment_mode_status_cnt
        data_type: Int
        description: "The number of enrollment events for this mode that occurred in the given hour"
