version: 2

models:  
  - name: dim_course_blocks
    description: "A denormalized table of course block information. This should be preferred over dim_course_blocks_extended when section and subsection names are not necessary to include in a model"
    columns:
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: course_name
        data_type: String
        description: '{{ doc("course_name") }}'
      - name: course_run
        data_type: String
        description: '{{ doc("course_run") }}'
      - name: block_id
        data_type: String
        description: '{{ doc("block_id") }}'
      - name: block_name
        data_type: String
        description: "The block's name"
      - name: section_number
        data_type: String
        description: '{{ doc("section_number") }}'
      - name: subsection_number
        data_type: String
        description: '{{ doc("subsection_number") }}'  
      - name: hierarchy_location
        data_type: String
        description: "The full section:subsection:unit hierarchy in which this block belongs"
      - name: display_name_with_location
        data_type: String
        description: "The block's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at block names and can help data consumers understand which block they are analyzing"
      - name: course_order
        data_type: Int32
        description: '{{ doc("course_order") }}'
      - name: graded
        data_type: Boolean
        description: '{{ doc("graded") }}'
      - name: block_type
        data_type: String
        description: "The type of block. This can be a section, subsection, unit, or the block type"
      - name: section_with_name
        data_type: String
        description: "The name of the section"
      - name: subsection_with_name
        data_type: String
        description: "The name of the subsection"

  - name: dim_course_block_names
    description: "An in-memory dictionary of course blocks with their display names and additional metadata. Only stores the most recent row per block location."
    columns:
      - name: location
        data_type: String
        description: "The location of the block"
      - name: block_name
        data_type: String
        description: "The name of the block"
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: graded
        data_type: Boolean
        description: '{{ doc("graded") }}'
      - name: display_name_with_location
        data_type: String
        description: "The block's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at block names and can help data consumers understand which block they are analyzing"
      - name: course_order
        data_type: Int32
        description: '{{ doc("course_order") }}'
      - name: section
        data_type: Int32
        description: "The section number that this block falls under in the course. Starts at 1."
      - name: subsection
        data_type: Int32
        description: "The subsection number that this block falls under in the section. Starts at 1."
      - name: unit
        data_type: Int32
        description: "The unit number that this block falls under in the subsection. Starts at 1."
      - name: dump_id
        data_type: UUID
        description: '{{ doc("dump_id") }}'
      - name: time_last_dumped
        data_type: String
        description: '{{ doc("time_last_dumped") }}'

  - name: dim_most_recent_course_blocks
    docs:
        node_color: '{{ var("color_event_sink") }}'
    description: "A materialized view of course blocks with their display names and additional metadata. Only stores the most recent row per block location."
    columns:
      - name: location
        data_type: String
        description: "The location of the block"
      - name: block_name
        data_type: String
        description: "The name of the block"
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: graded
        data_type: Boolean
        description: '{{ doc("graded") }}'
      - name: display_name_with_location
        data_type: String
        description: "The block's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at block names and can help data consumers understand which block they are analyzing"
      - name: course_order
        data_type: Int32
        description: '{{ doc("course_order") }}'

  - name: dim_course_names
    docs:
        node_color: '{{ var("color_event_sink") }}'
    description: "A dictionary of courses with their names"
    columns:
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: course_name
        data_type: String
        description: '{{ doc("course_name") }}'
      - name: course_run
        data_type: String
        description: '{{ doc("course_run") }}'
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: tags_str
        data_type: String
        description: "A list of tags associated with the course"
