version: 2

models:
  - name: fact_video_engagement
    description: "A dataset with one record representing the engagement of a learner with a video"
    columns:
      - name: org
        data_type: string
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: string
        description: '{{ doc("course_key") }}'
      - name: section_subsection_name
        data_type: string
        description: "The name of the section or the subsection"
      - name: content_level
        data_type: string
        description: "The content level of the video"
        data_tests:
          - accepted_values:
              values:
                - 'section'
                - 'subsection'
      - name: actor_id
        data_type: string
        description: '{{ doc("actor_id") }}'
      - name: section_subsection_video_engagement
        data_type: string
        description: "The engagement level of the learner with the video"
        data_tests:
          - accepted_values:
              values:
                - 'No videos viewed yet'
                - 'At least one video viewed'
                - 'All videos viewed'
      - name: block_id
        data_type: String
        description: '{{ doc("block_id") }}'
      - name: username
        data_type: String
        description: '{{ doc("username") }}'
      - name: name
        data_type: String
        description: '{{ doc("learner_name") }}'
      - name: email
        data_type: String
        description: '{{ doc("email") }}'

  - name: fact_video_segment_watches
    description: "Amount of time in seconds watched by each actor for every video"
    columns:
      - name: event_id
        data_type: uuid
        description: '{{ doc("event_id") }}'
      - name: org
        data_type: string
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: string
        description: '{{ doc("course_key") }}'
      - name: actor_id
        data_type: string
        description: '{{ doc("actor_id") }}'
      - name: object_id
        data_type: string
        description: '{{ doc("object_id") }}'
      - name: video_duration
        data_type: Int32
        description: "Total duration of the video"
      - name: watched_segment
        data_type: Int32
        description: "Watched second of the video"
      - name: rewatched
        data_type: boolean
        description: "If video second has been watched more than once"
      - name: time_stamp
        data_type: Time
        description: "Video second shown as a timestamp"
      - name: video_number
        data_type: String
        description: "Location of video with invisible padding"
      - name: video_name_location
        data_type: String
        description: "Name and section/subsection"
      - name: video_link
        data_type: String
        description: "HTML for link to video within the course"
      - name: section_with_name
        data_type: string
        description: '{{ doc("section_with_name") }}'
      - name: subsection_with_name
        data_type: string
        description: '{{ doc("subsection_with_name") }}'

  - name: fact_video_segments
    description: "Each second of every video that has been watched"
    columns:
      - name: org
        data_type: string
        description: '{{ doc("org") }}'
      - name: course_key
        data_type: string
        description: '{{ doc("course_key") }}'
      - name: actor_id
        data_type: string
        description: '{{ doc("actor_id") }}'
      - name: object_id
        data_type: string
        description: '{{ doc("object_id") }}'
      - name: video_duration
        data_type: Int32
        description: "Total duration of the video"
      - name: watched_segment
        data_type: Int32
        description: "Watched second of the video"
      - name: watch_count
        data_type: Int32
        description: "Number of times the segment has been watched"

  - name: video_playback_events
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "Events related to video playback"
    columns:
      - name: event_id
        data_type: uuid
        description: '{{ doc("event_id") }}'
      - name: emission_time_long
        data_type: DateTime64(6)
        description: 'Emission time with extra time digits'
      - name: emission_time
        data_type: DateTime
        description: '{{ doc("emission_time") }}'
      - name: actor_id
        data_type: string
        description: '{{ doc("actor_id") }}'
      - name: object_id
        data_type: string
        description: '{{ doc("object_id") }}'
      - name: course_key
        data_type: string
        description: '{{ doc("course_key") }}'
      - name: org
        data_type: string
        description: '{{ doc("org") }}'
      - name: verb_id
        data_type: string
        description: '{{ doc("verb_id") }}'
      - name: video_position
        data_type: decimal(9, 2)
        description: "The position in the video where the event occurred"
      - name: video_duration
        data_type: int64
        description: "The duration of the video in seconds"

