version: 2

models:
  - name: xapi_events_all_parsed
    docs:
        node_color: '{{ var("color_xapi") }}'
    description: "A materialized view for xAPI events"
    columns:
      - name: event_id
        data_type: UUID
        description: '{{ doc("event_id") }}'
      - name: verb_id
        data_type: String
        description: '{{ doc("verb_id") }}'
      - name: actor_id
        data_type: String
        description: '{{ doc("actor_id") }}'
      - name: object_id
        data_type: String
        description: '{{ doc("object_id") }}'
      - name: course_id
        data_type: String
        description: "The fully-qualified course identifier URL"
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: org
        data_type: String
        description: '{{ doc("org") }}'
      - name: emission_time
        data_type: DateTime64(6)
        description: '{{ doc("emission_time") }}'
      - name: event
        data_type: String
        description: "The xAPI event as a String"
