version: 2

models:
  - name: xapi_events_all_parsed
    description: "A materialized view for xAPI events"
    columns:
      - name: event_id
        data_type: UUID
        description: "The unique identifier for the event"
      - name: verb_id
        data_type: String
        description: "The xAPI verb identifier"
      - name: actor_id
        data_type: String
        description: "The xAPI actor identifier"
      - name: object_id
        data_type: String
        description: "The xAPI object identifier"
      - name: course_id
        data_type: String
        description: "The fully-qualified course identifier URL"
      - name: course_key
        data_type: String
        description: "The course key for the course"
      - name: org
        data_type: String
        description: "The organization that the course belongs to"
      - name: emission_time
        data_type: DateTime64(6)
        description: "The time the event was emitted"
      - name: event
        data_type: String
        description: "The xAPI event as a String"
