version: 2

sources:
  - name: xapi
    database: "{{ env_var('ASPECTS_XAPI_DATABASE', 'xapi') }}"
    description: "the xapi database in clickhouse"
    tables:
      - name: xapi_events_all
        identifier: "{{ env_var('ASPECTS_VECTOR_RAW_XAPI_TABLE', 'xapi_events_all') }}"
        description: "Base table for raw xAPI events"
        columns:
          - name: event_id
          - name: emission_time
          - name: event

  - name: event_sink
    database: "{{ env_var('ASPECTS_EVENT_SINK_DATABASE', 'event_sink')}}"
    tables:
      - name: course_block_names
        columns:
          - name: location
          - name: block_name
          - name: course_key
          - name: graded
          - name: display_name_with_location

      - name: course_names
        columns:
          - name: course_key
          - name: course_name
          - name: course_run
          - name: org

      - name: user_pii
        columns:
          - name: user_id
            description: "The user id"
          - name: external_user_id
            description: "The external user id"
          - name: external_id_type
            description: "The external id type"
          - name: username
            description: "The username"
          - name: name
            description: "The name of the user"
          - name: meta
            description: "A field to store custom information as JSON"
          - name: courseware
            description: "Unknown"
          - name: language
            description: "The language of the user"
          - name: location
            description: "Unknown"
          - name: year_of_birth
            description: "The year of birth of the user"
          - name: gender
            description: "The gender of the user"
          - name: level_of_education
            description: "The level of education of the user"
          - name: mailing_address
            description: "The mailing address of the user"
          - name: city
            description: "The city of the user"
          - name: country
            description: "The country of the user"
          - name: state
            description: "The state of the user"
          - name: goals
            description: "The goals of the user"
          - name: bio
            description: "The bio of the user"
          - name: profile_image_uploaded_at
            description: "Date of the profile image upload"
          - name: phone_number
            description: "The phone number of the user"
