version: 2

sources:
  - name: xapi
    database: "{{ env_var('ASPECTS_XAPI_DATABASE', 'xapi') }}"
    description: "the xapi database in clickhouse"
    tables:
      - name: xapi_events_all
        identifier: "{{ env_var('ASPECTS_VECTOR_RAW_XAPI_TABLE', 'xapi_events_all') }}"
        description: "Base table for raw xAPI events"
        columns:
          - name: event_id
          - name: emission_time
          - name: event
          - name: event_str

  - name: event_sink
    database: "{{ env_var('ASPECTS_EVENT_SINK_DATABASE', 'event_sink')}}"
    tables:
      - name: course_block_names
        columns:
          - name: location
          - name: block_name
          - name: course_key
          - name: graded
          - name: display_name_with_location

      - name: course_names
        columns:
          - name: course_key
          - name: course_name
          - name: course_run
          - name: org
