version: 2

sources:
  - name: xapi
    database: "{{ env_var('ASPECTS_XAPI_DATABASE', 'xapi') }}"
    description: "the xapi database in clickhouse"
    tables:
      - name: xapi_events_all
        identifier: "{{ env_var('ASPECTS_VECTOR_RAW_XAPI_TABLE', 'xapi_events_all') }}"
        description: "Base table for raw xAPI events"
        columns:
          - name: event_id
          - name: emission_time
          - name: event
