version: 2

models:
  - name: navigation_events
    description: "A materialized view for xAPI events related to course navigation"
    columns:
      - name: event_id
        data_type: uuid
        description: "The unique identifier for the event"
      - name: emission_time
        data_type: datetime
        description: "Timestamp, to the second, of when this event was emitted"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: block_id
        data_type: string
        description: "The LMS object identifier"
      - name: course_key
        data_type: string
        description: "The course identifier"
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: verb_id
        data_type: string
        description: "The xAPI verb identifier"
      - name: object_type
        data_type: string
        description: "The type of object that the learner interacted with"
      - name: starting_position
        data_type: int64
        description: "The tab in the unit navigation bar that the learner was viewing before clicking a link"
      - name: ending_point
        data_type: string
        description: "The tab in the unit navigation bar that the learner selected to navigate to"

  - name: fact_navigation
    description: "A view of navigation_events enriched with course and block metadata"
    columns:
      - name: emission_time
        data_type: datetime
        description: "Timestamp, to the second, of when this event was emitted"
      - name: org
        data_type: string
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: string
        description: "The course identifier"
      - name: course_name
        data_type: string
        description: "The name of the course"
      - name: course_run
        data_type: string
        description: "The course run for the course"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: block_id
        data_type: string
        description: "The LMS object identifier"
      - name: block_name
        data_type: string
        description: "The block's name"
      - name: block_name_with_location
        data_type: string
        description: "The block's display name with section, subsection, and unit prepended to the name. This provides additional context when looking at block names and can help data consumers understand which block they are analyzing"
      - name: object_type
        data_type: string
        description: "The type of object that the learner interacted with"
      - name: starting_position
        data_type: int64
        description: "The tab in the unit navigation bar that the learner was viewing before clicking a link"
      - name: ending_point
        data_type: string
        description: "The tab in the unit navigation bar that the learner selected to navigate to"

  - name: fact_navigation_dropoff
    description: "A view for analyzing the number of page visits per learner per section and subsection"
    columns:
      - name: emission_date
        data_type: date
      - name: org
        data_type: string
      - name: course_key
        data_type: string
      - name: rollup_name
        data_type: string
        description: "The level at which page views are counted"
        tests:
          - accepted_values:
              values: ["section", "subsection"]
      - name: block_name
        data_type: string
      - name: actor_id
        data_type: string
      - name: total_views
        data_type: uint64
        description: "The total number of times a learner viewed pages in this section or subsection on a given day"

  - name: fact_navigation_completion
    description: "A view for analyzing how many pages a learner has visited in a section or subsection"
    columns:
      - name: visited_on
        data_type: date
      - name: org
        data_type: string
      - name: course_key
        data_type: string
      - name: section_with_name
        data_type: string
      - name: subsection_with_name
        data_type: string
      - name: page_count
        data_type: uint64
        description: "The number of pages in the associated subsection"
      - name: actor_id
        data_type: string
      - name: block_id
        data_type: string
        description: "The ID of the specific page visited"
