version: 2

models:
  - name: dim_most_recent_course_tags
    description: "Tag with lineage data for objects (view)"
    columns:
      - name: course_key
        data_type: String
        description: '{{ doc("course_key") }}'
      - name: course_name
        data_type: String
        description: '{{ doc("course_name") }}'
      - name: tag_id
        data_type: Int32
        description: "The ID of the tag"
      - name: tag
        data_type: String
        description: "The name of the tag"
      - name: lineage
        data_type: String
        description: "Lineage data of the tag for parent tags"
      - name: taxonomy_name
        data_type: String
        description: "The name of the parent taxonomy of the tag"

  - name: dim_most_recent_object_tags
    docs:
        node_color: '{{ var("color_event_sink") }}'
    description: "Latest object tags"
    columns:
      - name: id
        data_type: Int32
        description: '{{ doc("id") }}'
      - name: object_id
        data_type: String
        description: '{{ doc("object_id") }}'
      - name: taxonomy
        data_type: Int32
        description: "Foreign key to the taxonomy"
      - name: _value
        data_type: String
        description: "Tag string"
      - name: _export_id
        data_type: String
        description: "Export ID"
      - name: lineage
        data_type: String
        description: "Lineage data of the tag for parent tags"

  - name: dim_most_recent_tags
    docs:
        node_color: '{{ var("color_event_sink") }}'
    description: "Latest tags"
    columns:
      - name: id
        data_type: Int32
        description: '{{ doc("id") }}'
      - name: taxonomy
        data_type: Int32
        description: "Foreign key to the taxonomy"
      - name: parent
        data_type: Int32
        description: "Foreign key to the parent tag"
      - name: value
        data_type: String
        description: "Tag string"
      - name: external_id
        data_type: String
        description: "External ID"
      - name: lineage
        data_type: String
        description: "Lineage data of the tag for parent tags"

  - name: dim_most_recent_taxonomies
    docs:
        node_color: '{{ var("color_event_sink") }}'
    description: "Latest taxonomies"
    columns:
      - name: id
        data_type: Int32
        description: '{{ doc("id") }}'
      - name: name
        data_type: String
        description: "Name for the taxonomy"
